export const LOCATIONS: Record<string, string[]> = {
    "Aceh": ["Banda Aceh", "Langsa", "Lhokseumawe", "Sabang", "Subulussalam", "Kab. Aceh Barat", "Kab. Aceh Besar", "Kab. Pidie"],
    "Sumatera Utara": ["Medan", "Binjai", "Pematangsiantar", "Sibolga", "Tanjungbalai", "Tebing Tinggi", "Kab. Asahan", "Kab. Deli Serdang", "Kab. Karo"],
    "Sumatera Barat": ["Padang", "Bukittinggi", "Pariaman", "Padang Panjang", "Payakumbuh", "Sawahlunto", "Solok", "Kab. Agam", "Kab. Tanah Datar"],
    "Riau": ["Pekanbaru", "Dumai", "Kab. Bengkalis", "Kab. Kampar", "Kab. Siak", "Kab. Indragiri Hilir", "Kab. Rokan Hulu"],
    "Kepulauan Riau": ["Tanjungpinang", "Batam", "Kab. Bintan", "Kab. Karumun", "Kab. Natuna", "Kab. Lingga"],
    "Jambi": ["Jambi", "Sungai Penuh", "Kab. Batanghari", "Kab. Bungo", "Kab. Kerinci", "Kab. Merangin"],
    "Sumatera Selatan": ["Palembang", "Lubuklinggau", "Pagar Alam", "Prabumulih", "Kab. Banyuasin", "Kab. Lahat", "Kab. Musi Banyuasin"],
    "Bangka Belitung": ["Pangkalpinang", "Kab. Bangka", "Kab. Belitung", "Kab. Bangka Barat", "Kab. Bangka Tengah", "Kab. Bangka Selatan"],
    "Bengkulu": ["Bengkulu", "Kab. Bengkulu Selatan", "Kab. Bengkulu Utara", "Kab. Kaur", "Kab. Seluma", "Kab. Mukomuko"],
    "Lampung": ["Bandar Lampung", "Metro", "Kab. Lampung Barat", "Kab. Lampung Selatan", "Kab. Lampung Tengah", "Kab. Lampung Timur"],
    "DKI Jakarta": ["Jakarta Pusat", "Jakarta Utara", "Jakarta Barat", "Jakarta Selatan", "Jakarta Timur", "Kepulauan Seribu"],
    "Jawa Barat": ["Bandung", "Bekasi", "Bogor", "Cimahi", "Cirebon", "Depok", "Sukabumi", "Tasikmalaya", "Banjar", "Kab. Bandung", "Kab. Bandung Barat", "Kab. Bekasi", "Kab. Bogor", "Kab. Ciamis", "Kab. Cianjur", "Kab. Cirebon", "Kab. Garut", "Kab. Indramayu", "Kab. Karawang", "Kab. Kuningan", "Kab. Majalengka", "Kab. Pangandaran", "Kab. Purwakarta", "Kab. Subang", "Kab. Sukabumi", "Kab. Sumedang", "Kab. Tasikmalaya"],
    "Banten": ["Serang", "Cilegon", "Tangerang", "Tangerang Selatan", "Kab. Lebak", "Kab. Pandeglang", "Kab. Serang", "Kab. Tangerang"],
    "Jawa Tengah": ["Semarang", "Magelang", "Pekalongan", "Salatiga", "Surakarta", "Tegal", "Kab. Banjarnegara", "Kab. Banyumas", "Kab. Batang", "Kab. Blora", "Kab. Boyolali", "Kab. Brebes", "Kab. Cilacap", "Kab. Demak", "Kab. Grobogan", "Kab. Jepara", "Kab. Karanganyar", "Kab. Kebumen", "Kab. Kendal", "Kab. Klaten", "Kab. Kudus", "Kab. Magelang", "Kab. Pati", "Kab. Pekalongan", "Kab. Pemalang", "Kab. Purbalingga", "Kab. Purworejo", "Kab. Rembang", "Kab. Semarang", "Kab. Sragen", "Kab. Sukoharjo", "Kab. Tegal", "Kab. Temanggung", "Kab. Wonogiri", "Kab. Wonosobo"],
    "DI Yogyakarta": ["Yogyakarta", "Kab. Bantul", "Kab. Gunungkidul", "Kab. Kulon Progo", "Kab. Sleman"],
    "Jawa Timur": ["Surabaya", "Batu", "Blitar", "Kediri", "Madiun", "Malang", "Mojokerto", "Pasuruan", "Probolinggo", "Kab. Banyuwangi", "Kab. Blitar", "Kab. Bojonegoro", "Kab. Bondowoso", "Kab. Gresik", "Kab. Jember", "Kab. Jombang", "Kab. Kediri", "Kab. Lamongan", "Kab. Lumajang", "Kab. Madiun", "Kab. Magetan", "Kab. Malang", "Kab. Mojokerto", "Kab. Nganjuk", "Kab. Ngawi", "Kab. Pacitan", "Kab. Pamekasan", "Kab. Pasuruan", "Kab. Ponorogo", "Kab. Probolinggo", "Kab. Sampang", "Kab. Sidoarjo", "Kab. Situbondo", "Kab. Sumenep", "Kab. Trenggalek", "Kab. Tuban", "Kab. Tulungagung"],
    "Bali": ["Denpasar", "Kab. Badung", "Kab. Bangli", "Kab. Buleleng", "Kab. Gianyar", "Kab. Jembrana", "Kab. Karangasem", "Kab. Klungkung", "Kab. Tabanan"],
    "Nusa Tenggara Barat": ["Mataram", "Bima", "Kab. Bima", "Kab. Dompu", "Kab. Lombok Barat", "Kab. Lombok Tengah", "Kab. Lombok Timur", "Kab. Lombok Utara", "Kab. Sumbawa", "Kab. Sumbawa Barat"],
    "Nusa Tenggara Timur": ["Kupang", "Kab. Alor", "Kab. Belu", "Kab. Ende", "Kab. Flores Timur", "Kab. Kupang", "Kab. Lembata", "Kab. Malaka", "Kab. Manggarai", "Kab. Manggarai Barat", "Kab. Manggarai Timur", "Kab. Nagekeo", "Kab. Ngada", "Kab. Rote Ndao", "Kab. Sabu Raijua", "Kab. Sikka", "Kab. Sumba Barat", "Kab. Sumba Barat Daya", "Kab. Sumba Tengah", "Kab. Sumba Timur", "Kab. Timor Tengah Selatan", "Kab. Timor Tengah Utara"],
    "Kalimantan Barat": ["Pontianak", "Singkawang", "Kab. Bengkayang", "Kab. Kapuas Hulu", "Kab. Kayong Utara", "Kab. Ketapang", "Kab. Kubu Raya", "Kab. Landak", "Kab. Melawi", "Kab. Mempawah", "Kab. Sambas", "Kab. Sanggau", "Kab. Sekadau", "Kab. Sintang"],
    "Kalimantan Tengah": ["Palangka Raya", "Kab. Barito Selatan", "Kab. Barito Timur", "Kab. Barito Utara", "Kab. Gunung Mas", "Kab. Kapuas", "Kab. Katingan", "Kab. Kotawaringin Barat", "Kab. Kotawaringin Timur", "Kab. Lamandau", "Kab. Murung Raya", "Kab. Pulang Pisau", "Kab. Seruyan", "Kab. Sukamara"],
    "Kalimantan Selatan": ["Banjarmasin", "Banjarbaru", "Kab. Balangan", "Kab. Banjar", "Kab. Barito Kuala", "Kab. Hulu Sungai Selatan", "Kab. Hulu Sungai Tengah", "Kab. Hulu Sungai Utara", "Kab. Kotabaru", "Kab. Tabalong", "Kab. Tanah Bumbu", "Kab. Tanah Laut", "Kab. Tapin"],
    "Kalimantan Timur": ["Samarinda", "Balikpapan", "Bontang", "Kab. Berau", "Kab. Kutai Barat", "Kab. Kutai Kartanegara", "Kab. Kutai Timur", "Kab. Mahakam Ulu", "Kab. Paser", "Kab. Penajam Paser Utara"],
    "Kalimantan Utara": ["Tarakan", "Kab. Bulungan", "Kab. Malinau", "Kab. Nunukan", "Kab. Tana Tidung"],
    "Sulawesi Utara": ["Manado", "Bitung", "Kotamobagu", "Tomohon", "Kab. Bolaang Mongondow", "Kab. Bolaang Mongondow Selatan", "Kab. Bolaang Mongondow Timur", "Kab. Bolaang Mongondow Utara", "Kab. Kepulauan Sangihe", "Kab. Kepulauan Siau Tagulandang Biaro", "Kab. Kepulauan Talaud", "Kab. Minahasa", "Kab. Minahasa Selatan", "Kab. Minahasa Tenggara", "Kab. Minahasa Utara"],
    "Sulawesi Tengah": ["Palu", "Kab. Banggai", "Kab. Banggai Kepulauan", "Kab. Banggai Laut", "Kab. Buol", "Kab. Donggala", "Kab. Morowali", "Kab. Morowali Utara", "Kab. Parigi Moutong", "Kab. Poso", "Kab. Sigi", "Kab. Tojo Una-Una", "Kab. Tolitoli"],
    "Sulawesi Selatan": ["Makassar", "Palopo", "Parepare", "Kab. Bantaeng", "Kab. Barru", "Kab. Bone", "Kab. Bulukumba", "Kab. Enrekang", "Kab. Gowa", "Kab. Jeneponto", "Kab. Kepulauan Selayar", "Kab. Luwu", "Kab. Luwu Timur", "Kab. Luwu Utara", "Kab. Maros", "Kab. Pangkajene dan Kepulauan", "Kab. Pinrang", "Kab. Sidenreng Rappang", "Kab. Sinjai", "Kab. Soppeng", "Kab. Takalar", "Kab. Tana Toraja", "Kab. Toraja Utara", "Kab. Wajo"],
    "Sulawesi Tenggara": ["Kendari", "Baubau", "Kab. Bombana", "Kab. Buton", "Kab. Buton Selatan", "Kab. Buton Tengah", "Kab. Buton Utara", "Kab. Kolaka", "Kab. Kolaka Timur", "Kab. Kolaka Utara", "Kab. Konawe", "Kab. Konawe Kepulauan", "Kab. Konawe Selatan", "Kab. Konawe Utara", "Kab. Muna", "Kab. Muna Barat", "Kab. Wakatobi"],
    "Gorontalo": ["Gorontalo", "Kab. Boalemo", "Kab. Bone Bolango", "Kab. Gorontalo", "Kab. Gorontalo Utara", "Kab. Pohuwato"],
    "Sulawesi Barat": ["Mamuju", "Kab. Majene", "Kab. Mamasa", "Kab. Mamuju Tengah", "Kab. Pasangkayu", "Kab. Polewali Mandar"],
    "Maluku": ["Ambon", "Tual", "Kab. Buru", "Kab. Buru Selatan", "Kab. Kepulauan Aru", "Kab. Maluku Barat Daya", "Kab. Maluku Tengah", "Kab. Maluku Tenggara", "Kab. Maluku Tenggara Barat", "Kab. Seram Bagian Barat", "Kab. Seram Bagian Timur"],
    "Maluku Utara": ["Ternate", "Tidore Kepulauan", "Kab. Halmahera Barat", "Kab. Halmahera Tengah", "Kab. Halmahera Timur", "Kab. Halmahera Selatan", "Kab. Halmahera Utara", "Kab. Kepulauan Sula", "Kab. Pulau Morotai", "Kab. Pulau Taliabu"],
    "Papua": ["Jayapura", "Kab. Biak Numfor", "Kab. Jayapura", "Kab. Keerom", "Kab. Kepulauan Yapen", "Kab. Mamberamo Raya", "Kab. Sarmi", "Kab. Supiori", "Kab. Waropen"],
    "Papua Barat": ["Sorong", "Kab. Fakfak", "Kab. Kaimana", "Kab. Manokwari", "Kab. Manokwari Selatan", "Kab. Maybrat", "Kab. Pegunungan Arfak", "Kab. Raja Ampat", "Kab. Sorong", "Kab. Sorong Selatan", "Kab. Tambrauw", "Kab. Teluk Bintuni", "Kab. Teluk Wondama"],
    "Papua Tengah": ["Nabire", "Kab. Deiyai", "Kab. Dogiyai", "Kab. Intan Jaya", "Kab. Mimika", "Kab. Paniai", "Kab. Puncak", "Kab. Puncak Jaya"],
    "Papua Pegunungan": ["Wamena", "Kab. Jayawijaya", "Kab. Lanny Jaya", "Kab. Mamberamo Tengah", "Kab. Nduga", "Kab. Pegunungan Bintang", "Kab. Tolikara", "Kab. Yahukimo", "Kab. Yalimo"],
    "Papua Selatan": ["Merauke", "Kab. Asmat", "Kab. Boven Digoel", "Kab. Mappi"],
    "Papua Barat Daya": ["Sorong", "Kab. Maybrat", "Kab. Raja Ampat", "Kab. Sorong Selatan", "Kab. Tambrauw"],
};

export const DISCIPLINES = [
    "Pengembang Aplikasi (Web/Mobile)",
    "Desain UI/UX & Produk",
    "Desain Grafis & Branding",
    "Penulisan Konten & Copywriting",
    "Pemasaran Digital & SEO",
    "Manajemen Media Sosial & Komunitas",
    "Produksi Video & Animasi",
    "Fotografi",
    "Penerjemahan & Lokalisasi",
    "Asisten Virtual & Admin",
    "Analisis Data & Sains",
    "Konsultan Bisnis",
    "Keuangan & Pajak",
    "Layanan Hukum",
    "Pertanian & Agribisnis",
    "Arsitektur & Desain Interior",
    "Pendidikan & Bimbingan Belajar",
    "Manajemen Acara (Event Organizer)",
    "Kesehatan & Kebugaran",
    "Lainnya"
];

export const CATEGORY_MAPPING: Record<string, string> = {
    "App Development (Web/Mobile)": "Pengembang Aplikasi (Web/Mobile)",
    "UI/UX & Product Design": "Desain UI/UX & Produk",
    "Graphic Design & Branding": "Desain Grafis & Branding",
    "Content Writing & Copywriting": "Penulisan Konten & Copywriting",
    "Digital Marketing & SEO": "Pemasaran Digital & SEO",
    "Social Media & Community Management": "Manajemen Media Sosial & Komunitas",
    "Video Production & Animation": "Produksi Video & Animasi",
    "Photography": "Fotografi",
    "Translation & Localization": "Penerjemahan & Lokalisasi",
    "Virtual Assistant & Admin": "Asisten Virtual & Admin",
    "Data Analysis & Science": "Analisis Data & Sains",
    "Business Consultant": "Konsultan Bisnis",
    "Finance & Tax": "Keuangan & Pajak",
    "Legal Services": "Layanan Hukum",
    "Agriculture & Agribusiness": "Pertanian & Agribisnis",
    "Architecture & Interior Design": "Arsitektur & Desain Interior",
    "Education & Tutoring": "Pendidikan & Bimbingan Belajar",
    "Event Management": "Manajemen Acara (Event Organizer)",
    "Health & Wellness": "Kesehatan & Kebugaran",
    "Others": "Lainnya"
};
